from enum import StrEnum


class ErrorCode(StrEnum):
    INVALID_URL = "INVALID_URL"
    RECORDING_NOT_FOUND = "RECORDING_NOT_FOUND"
    PASSCODE_REQUIRED = "PASSCODE_REQUIRED"
    INVALID_PASSCODE = "INVALID_PASSCODE"
    LOGIN_REQUIRED = "LOGIN_REQUIRED"
    DOWNLOAD_NOT_ALLOWED = "DOWNLOAD_NOT_ALLOWED"
    DOWNLOAD_URL_EXPIRED = "DOWNLOAD_URL_EXPIRED"
    HTTP_UNAUTHORIZED = "HTTP_UNAUTHORIZED"
    HTTP_FORBIDDEN = "HTTP_FORBIDDEN"
    HTTP_NOT_FOUND = "HTTP_NOT_FOUND"
    NETWORK_TIMEOUT = "NETWORK_TIMEOUT"
    CONNECTION_RESET = "CONNECTION_RESET"
    SERVER_ERROR = "SERVER_ERROR"
    PARTIAL_DOWNLOAD = "PARTIAL_DOWNLOAD"
    INVALID_MEDIA = "INVALID_MEDIA"
    FILE_SIZE_MISMATCH = "FILE_SIZE_MISMATCH"
    DISK_FULL = "DISK_FULL"
    USER_CANCELLED = "USER_CANCELLED"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"

